"""
Build the one-page CV, taking every VOLLEY number from analysis/results/*.json.

WHY THIS SCRIPT EXISTS
----------------------
My older resumes disagree with this repository and with each other. One describes VOLLEY as
"coilgun-based", superseded since mid-2025 (ADR-003). Another quotes "10-50 m/s" where the model
gives 16.4 m/s at the rated point and 13.0-18.3 m/s across the payload family. A third carries a
different email address.

That is the same class of failure as the paper drifting from the scripts, and it gets the same
fix: the numbers are not typed into the CV, they are read from the JSON the analysis emits. If the
operating point moves again, the CV moves with it.

Run:  python3 paper/cv/make_cv.py     ->  writes cv.tex, then build it with pdflatex
"""
import hashlib
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(HERE, "..", "..", "analysis", "results")


def load(name):
    with open(os.path.join(RESULTS, name)) as f:
        return json.load(f)


def facts():
    motor = load("motor_results.json")
    sizing = load("sizing.json")
    mass = load("mass_properties.json")
    field = load("field_verification.json")

    shot = motor["shot"]
    fam = motor["family"]

    f = {
        "v_exit": shot["v_exit"],
        "a_peak_g": shot["a_g"],
        "energy_kJ": sizing["energy_closure"]["drawn_net_J"] / 1000.0,
        "kt": motor["Kt_N_per_kA"],
        "v_fam_lo": min(v["v_exit"] for v in fam.values()),
        "v_fam_hi": max(v["v_exit"] for v in fam.values()),
        "midgap_T": field["double_midgap_peak_T"],
    }
    # Mass and dispersion keys have moved before; look them up defensively and report what is
    # missing rather than silently emitting a blank.
    for key, src, names in (
        ("mass_dry", mass, ("dry_kg",)),
        ("mass_wet", mass, ("loaded_kg",)),
        ("sled_kg", mass, ("sled_kg",)),
        ("disp_3sig", motor, ("closed_loop_3sigma",)),
    ):
        f[key] = next((src[n] for n in names if n in src), None)
    return f


TEMPLATE = r"""% GENERATED by paper/cv/make_cv.py -- do not edit by hand.
% VOLLEY numbers come from analysis/results/*.json. Re-run the analysis, re-run this.
% motor_results.json sha256[:16] at generation: @DIGEST@
\documentclass[9pt,a4paper]{extarticle}
\usepackage[top=9mm,bottom=8mm,left=11mm,right=11mm]{geometry}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
%% Latin Modern supplies scalable Type 1 outlines. The default EC fonts fall back to Type 3
%% bitmaps in the minimal TeX install and look soft when the PDF is rendered on screen.
\usepackage[hidelinks]{hyperref}
\pagestyle{empty}

%% enumitem and titlesec live in texlive-latex-extra, which tools/env-setup.sh deliberately does
%% NOT install -- it drags in a mesa/ruby chain that fails to configure in a minimal container.
%% So the tight lists and the section rule are done with base LaTeX instead. This keeps the CV
%% buildable from exactly the toolchain env-setup.sh provides, which is the point.
\newenvironment{tight}%
  {\begin{list}{\textbullet}{%
     \setlength{\leftmargin}{3.6mm}\setlength{\labelwidth}{2.2mm}%
     \setlength{\labelsep}{1.4mm}\setlength{\itemsep}{0.4pt}%
     \setlength{\parsep}{0pt}\setlength{\topsep}{1pt}}}%
  {\end{list}}
\newcommand{\cvsection}[1]{%
  \vspace{1.0ex}{\normalsize\bfseries\MakeUppercase{#1}}\\[-1.3ex]
  \rule{\linewidth}{0.4pt}\vspace{0.4ex}}
%% Title on its own line, then subtitle and date sharing the next one. The earlier version
%% put the date on line 1 with \hfill, which overflowed whenever the title was long and pushed
%% the date onto a third line.
\newcommand{\job}[3]{\textbf{#1}\\ \textit{#2}\hfill #3\vspace{0.3ex}}

\begin{document}

\begin{center}
{\LARGE\bfseries ADITYAVARDHAN MISHRA}\\[0.5ex]
Pune, Maharashtra, India \textbullet\ +91 840 885 4466 \textbullet\
\href{mailto:adityavardhanmishr@gmail.com}{adityavardhanmishr@gmail.com}\\
\href{https://www.linkedin.com/in/adityavardhanmishra/}{linkedin.com/in/adityavardhanmishra}
\textbullet\ \href{https://github.com/aaaaaaaaaaaavm/VOLLEY}{github.com/aaaaaaaaaaaavm/VOLLEY}\\[0.3ex]
BTech Mechanical Engineering, Symbiosis Institute of Technology (SIT), Pune \textbullet\ 2023--2027
\end{center}

\vspace{-1ex}
Working on electromagnetic satellite deployment. Five years on one question --- why CubeSats are still deployed with springs --- now a
complete design study with a published defect record, an independently cross-checked field model,
and every claim traceable to the script that produced it. Also hands-on: engine rebuilds, ECU
calibration, 2nd globally at IREC 2025. Seeking propulsion, structures, or test \& validation work.
\textbf{Recognised by the ISRO Chairman} for STEM outreach \textbullet\ Space Generation Advisory Council.

\cvsection{Space systems}

\job{VOLLEY, an electromagnetic orbital CubeSat deployer}{Independent, final-year project \textbullet\ IEEE manuscript in preparation}{2021--present}
\begin{tight}
  \item Architected a magazine-fed \textbf{ironless double-sided Halbach linear synchronous motor}
        that ejects \textbf{unmodified} 3U CubeSats at \textbf{@V_EXIT@\,m/s} (@V_FAM_LO@--@V_FAM_HI@\,m/s
        across the 1U--12U family) at \textbf{@A_PEAK_G@\,g} on \textbf{@ENERGY_KJ@\,kJ} per shot ---
        6.6 times the fastest published spring, inside standard CubeSat qualification loads.
  \item Selected the LSM over a coilgun in a documented architecture trade: a coilgun needs a
        conductive armature on the customer satellite, and its velocity advantage is capped by the
        payload's own g-limit. Verified against published work reaching 321\,m/s at
        $\sim$1350\,g --- roughly 100$\times$ CubeSat qualification.
  \item Derived the thrust constant \textbf{@KT@\,N per kA/m} from a winding-resolved model, then
        \textbf{wrote a 2-D magnetostatic FEM from the weak form} (scikit-fem, gmsh, 141k elements)
        to check it independently: agreement to \textbf{0.03\,\%}.
  \item Closed the system at \textbf{@MASS_DRY@\,kg dry}, and \textbf{published every defect found}
        --- 46 numbered open problems, with acceptance bands declared before each analysis ran.
        \textbf{Retracted my own claims when evidence went against them}: an independent propagator
        (GMAT) falsified a claim in the paper's abstract; my cost model contradicted the paper on
        which parts dominate; a literature review found prior art I had missed. Presented at
        \textbf{DRDO ARDE}, Pune (2021) and the \textbf{India Science Festival}, IISER Pune (2024).
\end{tight}

\job{Electromagnetic Launch System for Vertical Silo-Based Deployment}{Sole author \textbullet\ feasibility study, IEEE format}{2025}
\begin{tight}
  \item Applied the same magazine-fed electromagnetic launch architecture to a 500\,kg booster
        class: belt-feed indexing, pulsed coilgun ejection, ignition deferred to 20\,m altitude.
        \textbf{2.50--4.17\,MJ per launch} across a sourced 15--25\,\% efficiency band,
        \textbf{10.6--15.0 cycles/min} on a 1\,MW supply.
  \item \textbf{Selected a coilgun here and rejected one for the CubeSat deployer} --- the same
        trade, resolved oppositely, because both are sized by the payload's g-limit via
        $s_{\min}=v^2/2ng$. A 15\,m rail holds 8.5\,g against a 10--15\,g propellant grain; a
        1.5\,m track holds 10.7\,g against a 14\,g CubeSat. Two machines, one constraint.
\end{tight}

\job{Re-entry Parachute Deployment System}{IREC 2025, Team THRUST \textbullet\ Midland, Texas}{2025}
\begin{tight}
  \item \textbf{2nd place globally}, SDL Payload Challenge. Modelled aerodynamic drag, engineered
        structural reliability into the recovery mechanism, and validated the deployment sequence
        against failure modes (FMEA).
\end{tight}

\cvsection{Powertrain and mechanical}

\job{Powertrain Engineer}{Wrench Wielders Racing --- SIT Formula Student}{2025--present}
\begin{tight}
  \item Engine teardown, inspection and reassembly on the KTM 390 single-cylinder platform; ECU
        calibration, fuel mapping and throttle response; passed SAE India technical inspection.
        Drivetrain integration and packaging --- sprocket sizing, engine-to-chassis mounting, and
        weekly coordination with chassis, suspension and aero on weight distribution.
\end{tight}

\job{Founder \& Powertrain Lead}{Poona Motor Club, Pune}{2021--present}
\begin{tight}
  \item Raised output \textbf{46 $\rightarrow$ $\sim$60\,bhp} on an RE Super Meteor 650,
        \textbf{dyno-validated across the band}, by re-engineering combustion airflow (head
        porting, camshaft profiling, high-flow induction, exhaust scavenging) and rewriting
        Powertronic fuel and ignition maps for target AFR at every throttle position. Replicated on
        a client Interceptor 650.
  \item \textbf{Reverse-engineered Powertronic's obfuscated map binary} and built a dual-map editor
        so two calibrations could be compared side by side on the bike.
  \item Standardised diagnosis and tuning across four platforms (RE Sherpa 450, KTM 390, CB600RR,
        Duke 390); ground-up rebuild of a 2009 TVS Apache 180, ANSYS-validated chassis.
\end{tight}

\noindent\textbf{Two-Stage Gear Train Supercharger} --- \textbf{completed} (previous final-year
project, closed out in third year). Designed and metal-fabricated a two-stage spur gear train giving
\textbf{1:5 RPM multiplication} within cleared gear-stress margins, letting a standard high-torque DC
motor replace an ultra-high-speed unit; FMEA completed (ANSYS, MATLAB).

\cvsection{Applied AI and software}

%% Dates follow LinkedIn. An older resume shows "2021 - Present" for Avisys, which conflicts
%% with both LinkedIn and the 05/2025 on another version; LinkedIn is the structured record.
\job{AI System Architect}{Avisys Services \textbullet\ AI Associate, Sep 2025 -- Jan 2026}{Jan 2026--present}
\begin{tight}
  \item Own AI systems architecture and product design for AviateCX, an enterprise telecom CRM:
        shipped a \textbf{RAG} retrieval assistant (pipeline, vector store, prompt engineering) and a
        role-based dashboard across all four user tiers. Also architecting a multi-state Resource
        Adequacy compliance platform for Indian power utilities (GridPath, pandapower, Antares under
        a versioned regulatory-rules engine).
\end{tight}

\cvsection{Skills}

{\small\noindent\textbf{Simulation:} scikit-fem, gmsh, GetDP, CalculiX, ngspice, GMAT, magpylib ---
magnetostatic FEM, structural FEA, circuit, orbit propagation. \textbf{CAD/CAE:} Fusion 360,
SolidWorks, AutoCAD, ANSYS. \textbf{Programming:} Python (numpy/scipy), MATLAB, C, \LaTeX, git.
\textbf{Hardware:} fabrication, 3-D printing, CNC, ECU calibration, dyno testing, FMEA.
Coursework in Finite Element Methods and CFD. Every skill here is mapped to the file that evidences
it: \href{https://github.com/aaaaaaaaaaaavm/VOLLEY/blob/main/docs/SKILLS.md}{docs/SKILLS.md}.\par}

\end{document}
"""


def main():
    f = facts()
    missing = [k for k, v in f.items() if v is None]
    if missing:
        raise SystemExit(
            "Missing keys in analysis/results/*.json: " + ", ".join(missing) +
            "\nThe CV will not be written with blanks. Fix the lookup in facts() instead."
        )

    # LaTeX is full of % and \%, which Python's %-formatting cannot survive. Tokens instead.
    subs = {
        "@V_EXIT@":    f"{f['v_exit']:.1f}",
        "@V_FAM_LO@":  f"{f['v_fam_lo']:.1f}",
        "@V_FAM_HI@":  f"{f['v_fam_hi']:.1f}",
        "@A_PEAK_G@":  f"{f['a_peak_g']:.1f}",
        "@ENERGY_KJ@": f"{f['energy_kJ']:.2f}",
        "@KT@":        f"{f['kt']:.2f}",
        "@MASS_DRY@":  f"{f['mass_dry']:.1f}",
        # A CV that quotes six numbers cannot move for a change to a seventh, so a
        # byte-identical regeneration leaves tools/check_artifacts.py unable to tell
        # "not rebuilt" from "rebuilt, unchanged". The digest is of the whole results
        # file and moves whenever the operating point does.
        "@DIGEST@":    hashlib.sha256(open(os.path.join(
            RESULTS, "motor_results.json"), "rb").read()).hexdigest()[:16],
    }
    out = TEMPLATE
    for k, v in subs.items():
        out = out.replace(k, v)
    left = re.findall(r"@[A-Z_]+@", out)
    if left:
        raise SystemExit("Unsubstituted tokens remain: " + ", ".join(sorted(set(left))))

    dest = os.path.join(HERE, "cv.tex")
    with open(dest, "w") as fh:
        fh.write(out)

    print("CV numbers taken from analysis/results/:")
    for k in ("v_exit", "a_peak_g", "energy_kJ", "kt", "v_fam_lo", "v_fam_hi",
              "mass_dry", "mass_wet", "sled_kg", "disp_3sig", "midgap_T"):
        print(f"  {k:12s} {f[k]}")
    print(f"\n-> {os.path.relpath(dest)}")
    print("   build:  cd paper/cv && pdflatex cv.tex")


if __name__ == "__main__":
    main()
